name: User Flatpak
run-name: User Flatpak Builder
# ON MERGE TO MAIN RUN THIS
on:
  push:
    branches:
     - 'main'
jobs:
  Flatpak-Builder-Action:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-47
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - uses: flathub-infra/flatpak-github-actions/flatpak-builder@master
        with:
          bundle: dev.qwery.AddWater.flatpak
          manifest-path: build-aux/dev.qwery.AddWater.json